- name: nginx
  ansible.builtin.package:
    name: nginx
    state: present
- name: run nginx
  ansible.builtin.service:
    name: nginx
    state: started    
    enabled: yes

- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.import_role:
    name: myrole
    tasks_from: app-pre-req.yaml

- name: copy conf file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
    

- name: nginx restart
  ansible.builtin.service:
    name: nginx
    state: restarted        