- name: delete directory
  ansible.builtin.file:    
    path: /usr/share/nginx/html
    state: absent

- name: delete directory
  ansible.builtin.file:    
    path: /usr/share/nginx/html
    state: directory    

- name: Download code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip
  
- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html    
    remote_src: yes


